spring.application.name=Blogging API
spring.datasource.url=jdbc:postgresql://localhost:5432/Blog_Platform
spring.datasource.username=sa
spring.datasource.password=an15092005
spring.datasource.driver-class-name=org.postgresql.Driver